export default [
  {
    id: 1,
    type: 'jobOffer',
    company: 'Aple',
    jobTitle: 'Frontend developer',
    tech: ['javascript', 'react', 'webpack', 'node', 'css'],
    description: 'We are looking for frontend dev',
    city: 'Warsaw',
    address: 'Marszałkowska 45a',
    salary: 17000,
    currency: 'pln',
    latLng: [52.2464418, 21.1277591],
    ref: 'ref1',
    commute: {
      travelTime: '0',
      distance: '0',
    },
    active: true,
  },
  {
    id: 2,
    type: 'jobOffer',
    company: 'Microsoft',
    jobTitle: 'Frontend developer',
    tech: ['javascript', 'react', 'webpack', 'node', 'css'],
    description: 'We are looking for frontend dev',
    city: 'Warsaw',
    address: 'Marszałkowska 45a',
    salary: 17000,
    currency: 'pln',
    latLng: [52.22977, 21.01178],
    ref: 'ref2',
    commute: {
      travelTime: '0',
      distance: '0',
    },
    active: true,
  },
  {
    id: 3,
    type: 'jobOffer',
    company: 'Netflix',
    jobTitle: 'Frontend developer',
    tech: ['javascript', 'react', 'webpack', 'node', 'css'],
    description: 'We are looking for frontend dev',
    city: 'Warsaw',
    address: 'Marszałkowska 45a',
    salary: 18000,
    currency: 'pln',
    latLng: [52.23977, 21.02178],
    ref: 'ref3',
    commute: {
      travelTime: '0',
      distance: '0',
    },
    active: true,
  },
]
