export default [
  {
    id: 1,
    companyLogo: 'icons/icon.png',
    type: 'jobOffer',
    company: 'Apple',
    jobTitle: 'Frontend developer',
    tech: ['javascript', 'react', 'webpack', '.net', 'sass'],
    description: 'We are looking for frontend dev',
    city: 'Warsaw',
    jobCategory: 'frontend',
    contract: 'b2b',
    seniority: 'junior',
    address: 'Szeroka 12c',
    error: {
      enabled: false,
      message: '',
    },
    salary: {
      min: 13000,
      max: 17000,
    },
    holidays: 20,
    currency: 'pln',
    latLng: [52.2464418, 21.1277591],
    ref: 'ref1',
    commute: {
      travelTime: '0',
      distance: '0',
    },
    remote: 0,
    active: true,
    scoring: {
      enabled: false,
      salary: {
        salaryPerHour: 0,
        commuteTime: 0,
        holidays: 0,
        real: 0,
      },
    },
  },
  {
    id: 2,
    companyLogo: 'icons/icon.png',
    type: 'jobOffer',
    company: 'Microsoft',
    jobTitle: 'Frontend developer',
    tech: ['javascript', 'react', 'webpack', 'node', 'css'],
    description: 'We are looking for frontend dev',
    city: 'Warsaw',
    jobCategory: 'backend',
    contract: 'b2b',
    seniority: 'mid',
    address: 'Marszałkowska 45a',
    error: {
      enabled: false,
      message: '',
    },
    salary: {
      min: 12000,
      max: 15000,
    },
    holidays: 0,
    currency: 'pln',
    latLng: [52.22977, 21.01178],
    ref: 'ref2',
    commute: {
      travelTime: '0',
      distance: '0',
    },
    remote: 100,
    active: true,
    scoring: {
      enabled: false,
      salary: {
        salaryPerHour: 0,
        commuteTime: 0,
        holidays: 0,
        real: 0,
      },
    },
  },
  {
    id: 3,
    companyLogo: 'icons/icon.png',
    type: 'jobOffer',
    company: 'Netflix',
    jobTitle: 'Frontend developer',
    tech: ['javascript', 'angular.js', 'gulp', 'node', 'css'],
    description: 'We are looking for frontend dev',
    city: 'Warsaw',
    jobCategory: 'frontend',
    contract: 'b2b',
    seniority: 'senior',
    address: 'Obożna 7',
    error: {
      enabled: false,
      message: '',
    },
    salary: {
      min: 15000,
      max: 23000,
    },
    holidays: 15,
    currency: 'pln',
    latLng: [52.23977, 21.02178],
    ref: 'ref3',
    commute: {
      travelTime: '0',
      distance: '0',
    },
    remote: 50,
    active: true,
    scoring: {
      enabled: false,
      salary: {
        salaryPerHour: 0,
        commuteTime: 0,
        holidays: 0,
        real: 0,
      },
    },
  },
]
